name: HTML/a11y

on: push

jobs:
  build:
    name: Test HTML and accessibility with NU HTML Checker
    runs-on: ubuntu-20.04

    steps:
    - name: Run html-validator-cli
      run: |
        npm i -g html-validator-cli
        html-validator "https://airwptheme.com/demo" --format=text --quiet
