# @Author: Roni Laukkarinen
# @Date:   2023-02-15 17:39:37
# @Last Modified by:   Roni Laukkarinen
# @Last Modified time: 2023-02-15 19:45:32
name: Run JS related checks

on: push

jobs:
  build:
    name: Test JS
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Install packages
      run: |
        rm package.json
        wget https://raw.githubusercontent.com/digitoimistodude/devpackages/master/package.json
        npm i

    - name: Install air-light related packages
      run: |
        npm i -g airbnb-browser-shims@^3.3.0
        npm i -g moveto@^1.8.2
        npm i -g reframe.js@^4.0.0

    - name: Run checks with npm
      run: |
        npm link eslint --ignore-scripts
        eslint .
