# @Author: Roni Laukkarinen
# @Date:   2023-02-15 17:39:37
# @Last Modified by:   Roni Laukkarinen
# @Last Modified time: 2023-02-15 18:09:43
name: Run PHP related checks

on:
  workflow_dispatch

env:
  PHPCS_DIR: /tmp/phpcs
  PHPCOMPAT_DIR: /tmp/phpcompatibility
  SNIFFS_DIR: /tmp/sniffs

jobs:
  build:
    name: Test styles
    runs-on: ubuntu-20.04

    steps:
    - name: Set up and run PHPCS
      run: |
        git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
        git clone -b 2.2.1 --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $WPCS_DI
        $PHPCS_DIR/bin/phpcs --config-set installed_paths $WPCS_DIR,$PHPCOMPAT_DIR,$SNIFFS_DIR
        git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $PHPCOMPAT_DIR
        wget https://raw.githubusercontent.com/digitoimistodude/air-light/master/phpcs.xml
        find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
        $PHPCS_DIR/bin/phpcs -p . --ignore=node_modules,*/css/* --standard=phpcs.xml
