# @Author: Roni Laukkarinen
# @Date:   2023-02-15 17:39:37
# @Last Modified by:   Roni Laukkarinen
# @Last Modified time: 2023-02-15 19:50:15
name: Run style related checks

on: push

jobs:
  build:
    name: Test styles
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Install packages from devpackages
      run: |
        rm package.json
        wget https://raw.githubusercontent.com/digitoimistodude/devpackages/master/package.json
        npm i -g husky
        npm i

    - name: Run checks with npm
      run: |
        npm i
        stylelint . --max-warnings 0 --config .stylelintrc
